//
// Generated file, do not edit! Created by opp_msgtool 6.0 from message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Message;
/**
 * Class generated from <tt>message.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Message
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     int Header;
 *     string Payload;
 *     char Trailer;
 *     int Type;
 *     int Ack_no;
 * }
 * </pre>
 *
 * Message_Base is only useful if it gets subclassed, and Message is derived from it.
 * The minimum code to be written for Message is the following:
 *
 * <pre>
 * class Message : public Message_Base
 * {
 *   private:
 *     void copy(const Message& other) { ... }

 *   public:
 *     Message(const char *name=nullptr, short kind=0) : Message_Base(name,kind) {}
 *     Message(const Message& other) : Message_Base(other) {copy(other);}
 *     Message& operator=(const Message& other) {if (this==&other) return *this; Message_Base::operator=(other); copy(other); return *this;}
 *     virtual Message *dup() const override {return new Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(Message)
 * </pre>
 */
class Message_Base : public ::omnetpp::cPacket
{
  protected:
    int Header = 0;
    omnetpp::opp_string Payload;
    char Trailer = 0;
    int Type = 0;
    int Ack_no = 0;

  private:
    void copy(const Message_Base& other);

  protected:
    bool operator==(const Message_Base&) = delete;

    // make assignment operator protected to force the user override it
    Message_Base& operator=(const Message_Base& other);

  public:
    // make constructors protected to avoid instantiation
    Message_Base(const char *name=nullptr, short kind=0);
    Message_Base(const Message_Base& other);
    virtual ~Message_Base();
    virtual Message_Base *dup() const override {return new Message_Base(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHeader() const;
    virtual void setHeader(int Header);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * Payload);

    virtual char getTrailer() const;
    virtual void setTrailer(char Trailer);

    virtual int getType() const;
    virtual void setType(int Type);

    virtual int getAck_no() const;
    virtual void setAck_no(int Ack_no);
};


namespace omnetpp {

template<> inline Message_Base *fromAnyPtr(any_ptr ptr) { return check_and_cast<Message_Base*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGE_M_H

